import { authService } from './authService';
import prisma from '../utils/prisma';

export interface CreateBuyerInput {
  userId: string;
  firstName?: string;
  lastName?: string;
  dateOfBirth?: string;
  phoneNumber: string;
  email: string;
  address?: string;
  gender?: string;
  idType?: string;
  idNumber?: string;
  nin?: string;
  bvn?: string;
  photo?: string;
  profileImageUrl?: string;
  state?: string;
  lga?: string;
  streetName?: string;
  buildingNumber?: string;
  zipCode?: string;
  password: string;
}

export interface UpdateBuyerInput {
  firstName?: string;
  lastName?: string;
  DOB?: string;
  phoneNumber?: string;
  email?: string;
  address?: string;
  gender?: string;
  idType?: string;
  idNumber?: string;
  nin?: string;
  bvn?: string;
  photo?: string;
  profileImageUrl?: string;
  state?: string;
  LGA?: string;
  streetName?: string;
  houseNo?: string;
  zipCode?: string;
}

const buyerSelect = {
  splitrId: true,
  id: true,
  userId: true,
  firstName: true,
  lastName: true,
  phoneNumber: true,
  email: true,
  isVerified: true,
  createdAt: true,
  updatedAt: true,
  nin: true,
  bvn: true,
  address: true,
} as const;

export class BuyerService {
  async createBuyer(input: CreateBuyerInput) {
    const { email, phoneNumber } = input;

    if (!phoneNumber) {
      throw new Error('Phone number is required');
    }
    if (!email) {
      throw new Error('Email is required');
    }

    const existingByContact = await prisma.buyer.findFirst({
      where: { OR: [{ email }] },
    });
    if (existingByContact) {
      throw new Error('Buyer with provided email already exists');
    }
    // Also check if nin already exists
    const existingNin = await prisma.buyer.findFirst({
      where: { nin: input.nin },
    });
    if (existingNin) {
      throw new Error('Nin already exists for another buyer');
    }

    const newUser = await authService.create({
      email: input.email,
      password: input.password,
      firstName: input.firstName,
      lastName: input.lastName,
      phoneNumber: input.phoneNumber,
      role: 'Buyer',
      userType: 'Buyer',
      isVerified: false,
      isPhoneVerified: true,
      isEmailVerified: true,
      isActive: true,
      profileImageUrl: input.profileImageUrl,
      // address: input.address,
    });
    if (!newUser) {
      throw new Error('User not created');
    }
    input.userId = newUser.data.user.id;
    const buyer = await prisma.buyer.create({
      data: {
        splitrId: '', // Will be auto-generated by trigger
        userId: input.userId,
        firstName: input.firstName,
        lastName: input.lastName,
        DOB: input.dateOfBirth,
        phoneNumber,
        email,
        address: input.address,
        gender: input.gender,
        nin: input.nin,
        bvn: input.bvn,
        photo: input.photo,
        state: input.state,
        LGA: input.lga,
        streetName: input.streetName,
        houseNo: input.buildingNumber,
        zipCode: input.zipCode,
        isVerified: true,
        isPhoneVerified: true,
        isEmailVerified: true,
        isActive: true,
      },
      select: buyerSelect,
    });

    return buyer;
  }

  async getBuyerById(id: string) {
    const buyer = await prisma.buyer.findUnique({
      where: { id },
      select: buyerSelect,
    });
    if (!buyer) {
      throw new Error('Buyer not found');
    }
    return buyer;
  }

  async listBuyers() {
    const buyers = await prisma.buyer.findMany({
      select: buyerSelect,
      orderBy: { createdAt: 'desc' },
    });
    return buyers;
  }

  async updateBuyer(id: string, data: UpdateBuyerInput) {
    const existing = await prisma.buyer.findUnique({ where: { id } });
    if (!existing) {
      throw new Error('Buyer not found');
    }

    if (data.email || data.phoneNumber) {
      const byContact = await prisma.buyer.findFirst({
        where: {
          AND: [
            { id: { not: id } },
            {
              OR: [
                data.email ? { email: data.email } : undefined,
                data.phoneNumber ? { phoneNumber: data.phoneNumber } : undefined,
              ].filter(Boolean) as any,
            },
          ],
        },
      });
      if (byContact) {
        throw new Error('Another buyer exists with provided email or phone');
      }
    }

    const buyer = await prisma.buyer.update({
      where: { id },
      data,
      select: buyerSelect,
    });
    return buyer;
  }

  async deleteBuyer(id: string) {
    const existing = await prisma.buyer.findUnique({ where: { id } });
    if (!existing) {
      throw new Error('Buyer not found');
    }
    await prisma.buyer.delete({ where: { id } });
    return { message: 'Buyer deleted successfully' };
  }

  /**
   * Get total number of active buyers
   * Active buyers are those who are verified and not deleted
   */
  async getTotalActiveBuyers(): Promise<number> {
    try {
      const count = await prisma.buyer.count({
        where: {
          isVerified: true,
        },
      });
      return count;
    } catch (error) {
      console.error('Error getting total active buyers:', error);
      throw new Error('Failed to get total active buyers');
    }
  }

  /**
   * Get buyers created within a date range
   */
  async getBuyersCreatedByDateRange(startDate: Date, endDate: Date) {
    try {
      // Validate dates
      if (!startDate || !endDate) {
        throw new Error('Start date and end date are required');
      }

      if (startDate > endDate) {
        throw new Error('Start date must be before or equal to end date');
      }

      const where: any = {
        createdAt: {
          gte: startDate,
          lte: endDate,
        },
      };

      // Get total count
      const totalCount = await prisma.buyer.count({ where });

      // Get counts by verification status
      const verifiedCount = await prisma.buyer.count({
        where: { ...where, isVerified: true },
      });

      const unverifiedCount = await prisma.buyer.count({
        where: { ...where, isVerified: false },
      });

      const activeCount = await prisma.buyer.count({
        where: { ...where, isActive: true },
      });

      // Get buyers with basic info
      const buyers = await prisma.buyer.findMany({
        where,
        select: {
          id: true,
          splitrId: true,
          firstName: true,
          lastName: true,
          email: true,
          phoneNumber: true,
          isVerified: true,
          isActive: true,
          createdAt: true,
        },
        orderBy: { createdAt: 'desc' },
      });

      return {
        success: true,
        data: {
          dateRange: {
            startDate: startDate.toISOString(),
            endDate: endDate.toISOString(),
          },
          totalCount,
          verifiedCount,
          unverifiedCount,
          activeCount,
          buyers,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get buyers count grouped by day within a date range
   */
  async getBuyersCountGroupedByDay(startDate: Date, endDate: Date) {
    try {
      // Validate dates
      if (!startDate || !endDate) {
        throw new Error('Start date and end date are required');
      }

      if (startDate > endDate) {
        throw new Error('Start date must be before or equal to end date');
      }

      // Get all buyers in the date range
      const buyers = await prisma.buyer.findMany({
        where: {
          createdAt: {
            gte: startDate,
            lte: endDate,
          },
        },
        select: {
          createdAt: true,
        },
      });

      // Create a map to store counts by date
      const countsByDate = new Map<string, number>();

      // Generate all dates in the range
      const currentDate = new Date(startDate);
      currentDate.setHours(0, 0, 0, 0);
      const endDateNormalized = new Date(endDate);
      endDateNormalized.setHours(23, 59, 59, 999);

      // Initialize all dates with 0 count
      while (currentDate <= endDateNormalized) {
        const dateKey = currentDate.toISOString().split('T')[0];
        countsByDate.set(dateKey, 0);
        currentDate.setDate(currentDate.getDate() + 1);
      }

      // Count buyers for each date
      buyers.forEach((buyer) => {
        const dateKey = buyer.createdAt.toISOString().split('T')[0];
        const currentCount = countsByDate.get(dateKey) || 0;
        countsByDate.set(dateKey, currentCount + 1);
      });

      // Convert map to array
      const countsByDay = Array.from(countsByDate.entries()).map(([date, count]) => ({
        date,
        count,
      }));

      // Calculate total
      const totalCount = buyers.length;

      return {
        success: true,
        data: {
          dateRange: {
            startDate: startDate.toISOString(),
            endDate: endDate.toISOString(),
          },
          totalCount,
          countsByDay,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }
}

export const buyerService = new BuyerService();
