import {
  InvoiceStatus,
  InvoiceType,
  LoanStatus,
  LoanType,
  MerchantTransactionType,
  TransactionStatus,
  MandateStatus,
  DirectPayStatus,
  RevenueType,
  LoanReturnStatus,
  PaystackTransferStatus,
  LoanInstallmentType,
} from "@prisma/client";
import { loanService } from "./loanService";
import { LoanSettingService } from "./loanSettingService";
import { MerchantTransactionService } from "./merchantTransactionService";
import { emailService } from "./emailService";
import { RevenueService } from "./revenueService";
import { invoiceMandateService } from "./invoiceMandateService";
import { randomBytes } from "crypto";
import { accountDetailsService } from "./accountDetailsService";
import { directPayService } from "./directPayService";
import prisma from "../utils/prisma";
import { buyerService } from "./buyerService";
import { paystackMerchantTransferRecipientService } from "./paystackMerchantTransferRecipientService";
import { paystackTransferService } from "./paystackTransferService";
import { paystackService } from "./paystackService";

const loanSettingService = new LoanSettingService();
const merchantTransactionService = new MerchantTransactionService();
const revenueService = new RevenueService();

// ==================== HELPER FUNCTIONS ====================

/**
 * Generate a short alphanumeric reference ID (max 24 characters)
 * @returns A string containing only alphanumeric characters (0-9, A-Z)
 */
export const generateShortReferenceId = (): string => {
  // Generate 12 random bytes (96 bits) for good entropy
  const bytes = randomBytes(12);
  // Convert to hex and then map to alphanumeric (0-9, A-Z)
  // Hex gives us 24 characters, we'll convert a-f to A-F and keep 0-9
  const hex = bytes.toString("hex").toUpperCase();

  // Take first 24 characters (hex is always 24 chars for 12 bytes)
  // Hex already contains only 0-9 and A-F, which are alphanumeric
  return hex.substring(0, 24);
};

// ==================== INTERFACES ====================

export interface CreateItemInput {
  description: string;
  quantity: number;
  amount: number;
}

export interface UpdateItemInput {
  description?: string;
  quantity?: number;
  amount?: number;
}

export interface CreateInvoiceInput {
  customerName: string;
  customerEmail: string;
  customerPhoneNumber: string;
  dueDate: Date | string;
  note?: string;
  amount: number;
  buyerId?: string;
  merchantId: string;
  items: CreateItemInput[];
  status?: InvoiceStatus;
  type?: InvoiceType;
}

export interface UpdateInvoiceInput {
  customerName?: string;
  customerEmail?: string;
  customerPhoneNumber?: string;
  dueDate?: Date | string;
  note?: string;
  amount?: number;
  buyerId?: string;
  status?: InvoiceStatus;
  type?: InvoiceType;
  items?: UpdateItemInput[];
  returnStatus?: LoanReturnStatus;
  returnReference?: string;
  returnReason?: string;
  returnNote?: string;
  returnInitiatedDate?: Date | string;
  // Backward compatibility alias; mapped to returnInitiatedDate.
  returnDate?: Date | string;
  returnApprovedBy?: string;
  returnApprovedDate?: Date | string;
  returnInitiatedBy?: string;
}

// ==================== SELECT OBJECTS ====================

const invoiceSelect = {
  id: true,
  splitrId: true,
  customerName: true,
  customerEmail: true,
  customerPhoneNumber: true,
  dueDate: true,
  note: true,
  amount: true,
  buyerId: true,
  merchantId: true,
  status: true,
  type: true,
  createdAt: true,
  updatedAt: true,
} as const;

const itemSelect = {
  id: true,
  invoiceId: true,
  description: true,
  quantity: true,
  amount: true,
  createdAt: true,
  updatedAt: true,
} as const;

const INTERST_RATE = process.env.INTERST_RATE || 7.5;
// ==================== INVOICE SERVICE ====================

export class InvoiceService {
  // ==================== INVOICE CRUD ====================

  /**
   * Create a new invoice with items
   */
  async createInvoice(input: CreateInvoiceInput) {
    try {
      // Validate merchant exists
      const merchant = await prisma.merchant.findUnique({
        where: { id: input.merchantId },
      });

      if (!merchant) {
        throw new Error("Merchant not found");
      }

      // Validate buyer if provided
      if (input.buyerId) {
        const buyer = await prisma.buyer.findUnique({
          where: { id: input.buyerId },
        });

        if (!buyer) {
          throw new Error("Buyer not found");
        }
      }

      // Validate items
      if (!input.items || input.items.length === 0) {
        throw new Error("Invoice must have at least one item");
      }

      // Create invoice with items
      const invoice = await prisma.invoice.create({
        data: {
          splitrId: "", // Will be auto-generated by trigger
          customerName: input.customerName,
          customerEmail: input.customerEmail,
          customerPhoneNumber: input.customerPhoneNumber,
          dueDate: new Date(input.dueDate),
          note: input.note,
          amount: input.amount,
          buyerId: input.buyerId,
          merchantId: input.merchantId,
          status: input.status || InvoiceStatus.Pending,
          type: input.type || InvoiceType.Purchase,
          items: {
            create: input.items.map((item) => ({
              description: item.description,
              quantity: item.quantity,
              amount: item.amount,
            })),
          },
        },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          loan: {
            select: {
              id: true,
            },
          },
        },
      });

      // Send invoice email to customer
      try {
        const formattedDueDate = new Date(invoice.dueDate).toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        });

        const formattedItems = invoice.items.map((item) => ({
          description: item.description,
          quantity: item.quantity,
          amount: Number(item.amount).toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }),
        }));

        const formattedTotal = Number(invoice.amount).toLocaleString("en-US", {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        });
        emailService.sendTemplateEmail({
          to: invoice.customerEmail,
          templateName: "invoiceCreated",
          subject: `New Invoice from ${invoice.merchant.businessName} - ${invoice.splitrId}`,
          data: {
            customer_name: invoice.customerName,
            merchant_name: invoice.merchant.businessName,
            merchant_email: invoice.merchant.businessEmail,
            invoice_id: invoice.splitrId,
            due_date: formattedDueDate,
            items: formattedItems,
            total_amount: formattedTotal,
            note: invoice.note || "",
            invoice_link: `${
              process.env.FRONTEND_URL || "https://splitr.co"
            }/buyer/dashboard/invoices`,
          },
        });
      } catch (emailError: any) {
        // Log email error but don't fail the invoice creation
        console.error("Failed to send invoice email:", emailError.message);
      }

      return {
        success: true,
        message: "Invoice created successfully",
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to create invoice",
      };
    }
  }

  /**
   * Get invoice by ID
   */
  async getInvoiceById(id: string) {
    try {
      const invoice = await prisma.invoice.findUnique({
        where: { id },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
              phoneNumber: true,
            },
          },
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
              businessPhone: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }

      return {
        success: true,
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoice",
      };
    }
  }

  /**
   * Get invoice by splitrId
   */
  async getInvoiceBysplitrId(splitrId: string) {
    try {
      const invoice = await prisma.invoice.findUnique({
        where: { splitrId },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
              phoneNumber: true,
            },
          },
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
              businessPhone: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }

      return {
        success: true,
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoice",
      };
    }
  }

  /**
   * Get all invoices with optional filters
   */
  async getAllInvoices(filters?: {
    merchantId?: string;
    buyerId?: string;
    status?: InvoiceStatus;
    customerEmail?: string;
    q?: string;
    type?: InvoiceType;
    page?: number;
    limit?: number;
  }) {
    try {
      const page = filters?.page || 1;
      const limit = filters?.limit || 10;
      const skip = (page - 1) * limit;

      const where: any = {};
      if (filters?.merchantId) where.merchantId = filters.merchantId;
      if (filters?.buyerId) where.buyerId = filters.buyerId;
      if (filters?.status) where.status = filters.status;
      if (filters?.customerEmail) where.customerEmail = filters.customerEmail;
      if (filters?.type) where.type = filters.type;
      if (filters?.q) {
        where.OR = [
          { splitrId: { contains: filters.q } },
          { customerName: { contains: filters.q } },
          { customerPhoneNumber: { contains: filters.q } },
          { customerEmail: { contains: filters.q } },
        ];
      }

      const [invoices, total] = await Promise.all([
        prisma.invoice.findMany({
          where,
          skip,
          take: limit,
          include: {
            items: true,
            buyer: {
              select: {
                id: true,
                splitrId: true,
                firstName: true,
                lastName: true,
                email: true,
              },
            },
            merchant: {
              select: {
                id: true,
                splitrId: true,
                businessName: true,
                businessEmail: true,
              },
            },
            loan: {
              select: {
                id: true,
                downPaymentAmount: true,
                loanAmount: true,
                loanTenure: true,
                monthlyRepayment: true,
              },
            },
          },
          orderBy: { createdAt: "desc" },
        }),
        prisma.invoice.count({ where }),
      ]);

      return {
        success: true,
        data: {
          invoices,
          pagination: {
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
          },
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Get invoices by merchant ID
   */
  async getInvoicesByMerchantId(merchantId: string, status?: InvoiceStatus) {
    try {
      const where: any = { merchantId };
      if (status) where.status = status;

      const invoices = await prisma.invoice.findMany({
        where,
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
      });

      return {
        success: true,
        data: invoices,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Get invoices by buyer ID
   */
  async getInvoicesByBuyerId(buyerId: string, status?: InvoiceStatus) {
    try {
      const where: any = { buyerId };
      if (status) where.status = status;
      const invoices = await prisma.invoice.findMany({
        where,
        include: {
          items: true,
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
      });

      return {
        success: true,
        data: invoices,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Get invoices by customer email
   */
  async getInvoicesByCustomerEmail(customerEmail: string, status?: InvoiceStatus) {
    try {
      const where: any = { customerEmail };
      if (status) where.status = status;

      const invoices = await prisma.invoice.findMany({
        where,
        include: {
          items: true,
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
      });

      return {
        success: true,
        data: invoices,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Update invoice
   */
  async finalizeAfterUpfrontAndMandate(mandateId: string) {
    // Re-fetch mandate and verify upfront payment if needed, then update invoice, create loan, and record revenue/merchant transaction
    const mandate = await prisma.invoiceMandate.findUnique({
      where: { id: mandateId },
    });
    if (!mandate) {
      throw new Error("Mandate not found");
    }

    // check upfront payment
    const upfrontPayment = await directPayService.getDirectPaysByMandateId(mandate.id);
    if (!upfrontPayment) {
      throw new Error("Upfront payment not found");
    }
    if (upfrontPayment?.length > 0 && upfrontPayment[0].status != "Completed") {
      const validateUpfrontPayment = await directPayService.verifyMonoDirectPay(
        upfrontPayment[0].reference
      );
      if (!validateUpfrontPayment.success && validateUpfrontPayment.data.status !== "successful") {
        return {
          success: false,
          message: "Upfront payment not yet completed",
          data: validateUpfrontPayment.data,
        };
      }
    }
    const buyerId = mandate.buyerId;
    const mandateInvoiceId = mandate.invoiceId;
    const mandateDownPayment = mandate.downPayment;
    const mandateTenure = mandate.tenure;

    const buyer = await prisma.buyer.findUnique({
      where: { id: buyerId },
    });
    if (!buyer) {
      throw new Error("Buyer not found");
    }
    const invoice = await prisma.invoice.findUnique({
      where: { id: mandateInvoiceId },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }
    const eligibilityAndScore = await loanSettingService.liveEligibilityPurchase({
      purchaseAmount: Number(invoice.amount),
      downPaymentAmount: Number(mandateDownPayment),
      months: Number(mandateTenure),
      buyerId: buyerId,
    });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    const updateData: any = {
      status: InvoiceStatus.Paid,
      buyerId: buyerId,
      customerName: `${buyer.firstName} ${buyer.lastName}`,
      customerEmail: buyer.email,
      customerPhoneNumber: buyer.phoneNumber,
    };

    if (!("approved" in eligibilityAndScore) || !eligibilityAndScore.approved) {
      return {
        success: false,
        message: "Eligibility and score not valid",
        data: eligibilityAndScore,
      };
    }

    const updatedInvoice = await prisma.invoice.update({
      where: { id: mandateInvoiceId },
      data: updateData,
      include: {
        items: true,
      },
    });

    // get loan by invoice number
    const loan = await loanService.getLoanByInvoiceId(mandateInvoiceId);
    if (loan && loan.success) {
      return {
        success: true,
        message: "Invoice updated successfully",
        data: {
          invoice: updatedInvoice,
          loan: loan.data,
        },
      };
    }
    const loanResult = await loanService.createLoan({
      buyerId: buyerId,
      loanAmount: eligibilityAndScore.approvedLoanAmount,
      loanTenure: Number(mandateTenure),
      loanStartDate: new Date(),
      loanStatus: LoanStatus.Active,
      loanType: LoanType.Personal,
      loanInterestRate: Number(INTERST_RATE),
      loanPurpose: "Loan",
      purchaseAmount: Number(invoice.amount),
      downPaymentAmount: eligibilityAndScore.requiredDownPayment,
      merchantId: invoice.merchantId,
      referenceNumber: invoice.splitrId,
      adminCharge: eligibilityAndScore.adminCharge,
      insurance: eligibilityAndScore.insurance,
      monthlyRepayment: eligibilityAndScore.monthlyRepayment,
      invoiceId: mandateInvoiceId,
    });

    if (!loanResult.success) {
      return {
        success: false,
        message: loanResult.error || "Failed to create loan after approving invoice",
      };
    }
    // perform merchant payment
    await merchantTransactionService.createMerchantTransaction({
      merchantId: invoice.merchantId,
      invoiceRef: invoice.id,
      credit: Number(invoice.amount),
      debit: 0,
      transactionType: MerchantTransactionType.Credit,
      description: `invoice credit on ${invoice.id}`,
      status: TransactionStatus.Completed,
      transactionDate: new Date(),
      groupReference: invoice.splitrId,
    });
    await revenueService.createRevenue({
      type: RevenueType.DownPayment,
      credit: eligibilityAndScore.requiredDownPayment,
      debit: 0,
      description: `Down payment for loan ${invoice.splitrId}`,
      parentTable: "invoice",
      referenceIds: [invoice.id],
      detail: `Down payment for loan ${invoice.splitrId}`,
      buyerId: buyerId,
      transactionDate: new Date(),
    });

    return {
      success: true,
      message: "Invoice updated successfully",
      data: {
        invoice: updatedInvoice,
        loan: loanResult.data,
      },
    };
  }
  async updateInvoice(id: string, input: UpdateInvoiceInput) {
    const willReturn = input.returnStatus === LoanReturnStatus.Approved;
    try {
      const existingInvoice = await prisma.invoice.findUnique({
        where: { id },
      });

      if (!existingInvoice) {
        throw new Error("Invoice not found");
      }

      // Validate buyer if provided
      if (input.buyerId) {
        const buyer = await prisma.buyer.findUnique({
          where: { id: input.buyerId },
        });

        if (!buyer) {
          throw new Error("Buyer not found");
        }
      }

      const updateData: any = {};
      if (input.customerName !== undefined) updateData.customerName = input.customerName;
      if (input.customerEmail !== undefined) updateData.customerEmail = input.customerEmail;
      if (input.customerPhoneNumber !== undefined)
        updateData.customerPhoneNumber = input.customerPhoneNumber;
      if (input.dueDate !== undefined) updateData.dueDate = new Date(input.dueDate);
      if (input.note !== undefined) updateData.note = input.note;
      if (input.amount !== undefined) updateData.amount = input.amount;
      if (input.buyerId !== undefined) updateData.buyerId = input.buyerId;
      if (input.status !== undefined) updateData.status = input.status;
      if (input.type !== undefined) updateData.type = input.type;
      if (input.returnStatus !== undefined) updateData.returnStatus = input.returnStatus;
      if (input.returnReference !== undefined) updateData.returnReference = input.returnReference;
      if (input.returnReason !== undefined) updateData.returnReason = input.returnReason;
      if (input.returnNote !== undefined) updateData.returnNote = input.returnNote;
      const returnInitiatedDate = input.returnInitiatedDate ?? input.returnDate;
      if (returnInitiatedDate !== undefined)
        updateData.returnInitiatedDate = new Date(returnInitiatedDate);
      if (input.returnApprovedBy !== undefined)
        updateData.returnApprovedBy = input.returnApprovedBy;
      if (input.returnApprovedDate !== undefined)
        updateData.returnApprovedDate = new Date(input.returnApprovedDate);
      if (input.returnInitiatedBy !== undefined)
        updateData.returnInitiatedBy = input.returnInitiatedBy;
      if (willReturn) updateData.status = InvoiceStatus.Cancelled;
      if (willReturn) {
        await loanService.penaltyEnforcement(new Date());
      }

      const invoice = await prisma.invoice.update({
        where: { id },
        data: updateData,
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          loan: {
            select: {
              id: true,
            },
          },
        },
      });
      //update items

      if (input.items) {
        await prisma.item.deleteMany({
          where: { invoiceId: id },
        });
        for (const item of input.items) {
          await prisma.item.create({
            data: {
              invoiceId: id,
              description: item.description || "",
              quantity: item.quantity || 0,
              amount: item.amount || 0,
            },
          });
        }
      }

      if (willReturn) {
        merchantTransactionService.createMerchantTransaction({
          merchantId: invoice.merchantId,
          invoiceRef: invoice.id,
          credit: 0,
          debit: Number(invoice.amount),
          transactionType: MerchantTransactionType.Refund,
          transactionDate: new Date(),
          description: `Refund of ${invoice.amount}`,
        });
        await revenueService.createRevenue({
          type: RevenueType.Refund,
          credit: 0,
          debit: Number(invoice.amount),
          description: `Refund of ${invoice.amount}`,
          parentTable: "invoice",
          referenceIds: [invoice.id],
          transactionDate: new Date(),
        });
        if (!invoice.loan?.id) {
          throw new Error("Loan not found for invoice");
        }
        await loanService.updateLoan(invoice.loan.id, {
          loanStatus: LoanStatus.Cancel,
        });
      }
      return {
        success: true,
        message: "Invoice updated successfully",
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to update invoice",
      };
    }
  }

  /**
   * Update invoice status
   */
  async updateInvoiceStatus(id: string, status: InvoiceStatus) {
    try {
      const existingInvoice = await prisma.invoice.findUnique({
        where: { id },
      });

      if (!existingInvoice) {
        throw new Error("Invoice not found");
      }

      const invoice = await prisma.invoice.update({
        where: { id },
        data: { status },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              splitrId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          merchant: {
            select: {
              id: true,
              splitrId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      return {
        success: true,
        message: `Invoice marked as ${status.toLowerCase()}`,
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to update invoice status",
      };
    }
  }

  /**
   * Delete invoice (and cascade delete items)
   */
  async deleteInvoice(id: string) {
    try {
      const existingInvoice = await prisma.invoice.findUnique({
        where: { id },
        include: { items: true },
      });

      if (!existingInvoice) {
        throw new Error("Invoice not found");
      }

      await prisma.invoice.delete({
        where: { id },
      });

      return {
        success: true,
        message: "Invoice deleted successfully",
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to delete invoice",
      };
    }
  }

  /**
   * Update invoice
   */
  async approveAndCreateLoanInvoice(
    id: string,
    loanTenure: number,
    downPaymentAmount: number,
    buyerId: string
  ): Promise<any>;
  async approveAndCreateLoanInvoice(
    id: string,
    loanTenure: number,
    downPaymentAmount: number,
    buyerId: string,
    regenerateMandate: boolean
  ): Promise<any>;
  async approveAndCreateLoanInvoice(
    id: string,
    loanTenure: number,
    downPaymentAmount: number,
    buyerId: string,
    regenerateMandate: boolean = false
  ) {
    const buyer = await prisma.buyer.findUnique({
      where: { id: buyerId },
    });
    if (!buyer) {
      throw new Error("Buyer not found");
    }
    const invoice = await prisma.invoice.findUnique({
      where: { id: id },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }
    const eligibilityAndScore = await loanSettingService.liveEligibilityPurchase({
      purchaseAmount: Number(invoice.amount),
      downPaymentAmount: downPaymentAmount,
      months: loanTenure,
      buyerId: buyerId,
    });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    const updateData: any = {
      status: InvoiceStatus.Pending,
      buyerId: buyerId,
      customerName: `${buyer.firstName} ${buyer.lastName}`,
      customerEmail: buyer.email,
      customerPhoneNumber: buyer.phoneNumber,
    };

    if (!("approved" in eligibilityAndScore) || !eligibilityAndScore.approved) {
      return {
        success: false,
        message: "Eligibility and score not valid",
        data: eligibilityAndScore,
      };
    }

    //Before creating the loan, check if mandate exists for the invoice and downpayment already paid

    const updatedInvoice = await prisma.invoice.update({
      where: { id: id },
      data: updateData,
      include: {
        items: true,
      },
    });

    // create invoice mandate
    //generate short alphanumeric referenceId (max 24 characters)
    const referenceId = generateShortReferenceId();

    // get latest account details for the buyer
    const latestAccountDetails =
      await accountDetailsService.getLatestAccountDetailsByBuyerId(buyerId);
    if (!latestAccountDetails) {
      throw new Error("Account details not yet linked to the buyer");
    }
    const accountDetails = await accountDetailsService.getMonoAccountById(
      latestAccountDetails.data?.accountId || ""
    );
    if (!accountDetails) {
      throw new Error("Account not found for the buyer! Try linking the account to the buyer.");
    }

    // verify customer id is valid
    const customer = await accountDetailsService.getMonoCustomerById(
      accountDetails.data?.data?.customer?.id || ""
    );
    if (!customer.success) {
      console.log("customer error", customer.error);
      throw new Error("Customer not found");
    }
    const { phone, address, identification_no, identification_type, bvn } = customer.data?.data;
    if (bvn && bvn.length === 11) {
      buyerService.updateBuyer(buyerId, {
        sinNumber: bvn,
      });
    }
    if (
      !phone ||
      phone === "" ||
      !address ||
      address === "" ||
      !identification_no ||
      identification_no === "" ||
      !identification_type ||
      identification_type === ""
    ) {
      //update the customer information
      await accountDetailsService.updateMonoCustomer(
        accountDetails.data?.data?.customer?.id || "",
        {
          ...((!phone || phone === "") && { phone: buyer.phoneNumber || "08032186222" }),
          ...((!address || address === "") && { address: buyer.address || "Abuja" }),
          ...((!identification_no || identification_no === "") && {
            identification_no: buyer.sinNumber || buyer.idNumber || "",
          }),
          ...((!identification_type || identification_type === "") && {
            identification_type: buyer.idType || "bvn",
          }),
        }
      );
    }
    let updateMandateUrl = "";

    const mandate = await invoiceMandateService.getMandatesByInvoiceId(id);
    if (mandate?.length > 0) {
      updateMandateUrl = mandate[0].updateMandateUrl || "";

      if (mandate[0].status != "Active" || regenerateMandate == true) {
        // cancel the mandate
        await accountDetailsService.cancelMonoMandate(mandate[0].monoMandateId || "");
        const createEmandate = await accountDetailsService.createVariableMandate({
          customerId: accountDetails.data?.data?.customer?.id,
          maxAmount: Math.ceil(Number(eligibilityAndScore.monthlyRepayment) * 100),
          startDate: new Date().toISOString(),
          endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toISOString(),
          reference: referenceId,
          description: `Repayment for ${updatedInvoice.customerName}`,
          name: updatedInvoice.customerName,
          email: updatedInvoice.customerEmail,
          phone: updatedInvoice.customerPhoneNumber,
        });

        // update the mandate
        await invoiceMandateService.updateInvoiceMandate(mandate[0].id, {
          monoMandateId: createEmandate.data?.data?.mandate_id || "",
          status: MandateStatus.Pending,
          updateMandateUrl: createEmandate.data?.data?.mono_url,
          monoAccountId: accountDetails.data?.data?.account?.id,
          tenure: loanTenure,
          downPayment: eligibilityAndScore.requiredDownPayment,
          referenceId: referenceId,
          amount: eligibilityAndScore.requiredDownPayment,
        });
        updateMandateUrl = createEmandate.data?.data?.mono_url || "";
      }
      if (mandate[0].status == "Active" && regenerateMandate == false) {
        // chech if direct pay exists for the mandate
        await directPayService.regenerateDirectPay(mandate[0].id);

        // initiate direct pay
        const directPay = await this.initiateUpfrontPayment(id);
        if (directPay.success && directPay.data?.directPay) {
          updateMandateUrl =
            (directPay.data.directPay as { monoUrl?: string | null }).monoUrl || "";
        }
      }
    } else {
      const createEmandate = await accountDetailsService.createVariableMandate({
        customerId: accountDetails.data?.data?.customer?.id,
        maxAmount: Math.ceil(Number(eligibilityAndScore.monthlyRepayment) * 100),
        startDate: new Date().toISOString(),
        endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toISOString(),
        reference: referenceId,
        description: `Repayment for ${updatedInvoice.customerName}`,
        name: updatedInvoice.customerName,
        email: updatedInvoice.customerEmail,
        phone: updatedInvoice.customerPhoneNumber,
      });

      await invoiceMandateService.createInvoiceMandate({
        invoiceId: id,
        monoMandateId: createEmandate.data?.data?.mandate_id || "",
        monoAccountId: accountDetails.data?.data?.account?.id || "",
        monoCustomerId: accountDetails.data?.data?.customer?.id || "",
        buyerId: buyerId,
        referenceId: referenceId,
        amount: Number(eligibilityAndScore.monthlyRepayment.toFixed(2)),
        updateMandateUrl: createEmandate.data?.data?.mono_url,
        tenure: loanTenure,
        downPayment: eligibilityAndScore.requiredDownPayment,
        status: MandateStatus.Pending,
      });
      updateMandateUrl = createEmandate.data?.data?.mono_url || "";
    }
    // initiate mandate

    // perform merchant payment

    return {
      success: true,
      message: "Invoice updated successfully",
      data: {
        invoice: updatedInvoice,
        updateMandateUrl: updateMandateUrl,
      },
    };
  }

  async validateMandate({ invoiceId, referenceId }: { invoiceId?: string; referenceId?: string }) {
    let mandate: any;

    if (referenceId) {
      mandate = await invoiceMandateService.getMandateByReferenceId(referenceId);
    }
    if (invoiceId) {
      const mandates = await invoiceMandateService.getMandatesByInvoiceId(invoiceId);
      if (mandates?.length > 0) {
        mandate = mandates[0];
      }
    }
    if (!mandate) {
      throw new Error("Mandate not found");
    }
    const mandateId = mandate.monoMandateId;
    const mandateStatus = mandate.status;
    const mandateAmount = mandate.amount;
    const mandateTenure = mandate.tenure;
    const mandateDownPayment = mandate.downPayment;
    const mandateReferenceId = mandate.referenceId;
    const mandateInvoiceId = mandate.invoiceId;
    const mandateBuyerId = mandate.buyerId;
    const mandateMonoAccountId = mandate.monoAccountId;
    const mandateMonoCustomerId = mandate.monoCustomerId;
    const invoiceAmount = mandate.invoice.amount;
    const monoMandate = await accountDetailsService.getMonoMandateById(mandateId);
    if (!monoMandate) {
      throw new Error("Mono mandate not found");
    }
    const monoMandateStatus = monoMandate.data?.data?.status;
    const monoMandateApproved = monoMandate.data?.data?.approved;
    if (monoMandateApproved) {
      //upd
      await invoiceMandateService.updateInvoiceMandate(mandate.id, {
        status: MandateStatus.Active,
      });
    }
    const eligibilityAndScore = await loanSettingService.liveEligibilityPurchase({
      purchaseAmount: Number(invoiceAmount),
      downPaymentAmount: mandateDownPayment,
      months: mandateTenure,
      buyerId: mandateBuyerId,
    });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    return {
      ...monoMandate,
      eligibilityAndScore: {
        ...eligibilityAndScore,
        invoiceId: mandateInvoiceId,
        mandateId,
        referenceId,
      },
    };
  }

  async initiateUpfrontPayment(invoiceId: string) {
    const referenceId = generateShortReferenceId();
    const invoice = await prisma.invoice.findUnique({
      where: { id: invoiceId },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }
    const mandate = await invoiceMandateService.getMandatesByInvoiceId(invoiceId);
    if (mandate?.length === 0) {
      throw new Error("Mandate not found");
    }
    const mandateDownPayment = mandate[0].downPayment;
    const mandateTenure = mandate[0].tenure;
    const mandateBuyerId = mandate[0].buyerId;
    const mandateMonoAccountId = mandate[0].monoAccountId;
    const mandateMonoCustomerId = mandate[0].monoCustomerId;
    const eligibilityAndScore = await loanSettingService.liveEligibilityPurchase({
      purchaseAmount: Number(invoice.amount),
      downPaymentAmount: Number(mandateDownPayment),
      months: Number(mandateTenure),
      buyerId: mandateBuyerId,
    });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    // check if direct pay exists for the mandate
    await directPayService.regenerateDirectPay(mandate[0].id);

    // Check if the result has the required properties (complex type)
    // Type guard to narrow the type
    if (
      typeof eligibilityAndScore !== "object" ||
      !("requiredDownPayment" in eligibilityAndScore) ||
      !("adminCharge" in eligibilityAndScore) ||
      !("insurance" in eligibilityAndScore)
    ) {
      throw new Error("Eligibility and score result does not contain required payment information");
    }

    // TypeScript now knows these properties exist
    const result = eligibilityAndScore as {
      requiredDownPayment: number;
      adminCharge: number;
      insurance: number;
    };

    let amount =
      Number(result.requiredDownPayment) + Number(result.adminCharge) + Number(result.insurance);
    //ensure amount is 2 decimal places
    amount = Number(amount.toFixed(2));
    const buyer = await buyerService.getBuyerById(mandate[0].buyerId);
    if (!buyer) {
      throw new Error("Buyer not found");
    }

    const directPay = await directPayService.initiateMonoDirectPay({
      amount: Number(amount.toFixed(2)) * 100,
      customerId: mandateMonoCustomerId,
      reference: referenceId,
      // account: mandateMonoAccountId,
      description: `Upfront payment for invoice ${invoice.splitrId}`,
      customer: {
        email: buyer.email,
        phone: buyer.phoneNumber || "",
        address: buyer.address || "",
        identity: {
          type: "bvn",
          number: buyer.sinNumber || buyer.idNumber || "",
        },
        name: `${buyer.firstName} ${buyer.lastName}`,
      },
    });
    if (!directPay.success) {
      throw new Error("Failed to initiate upfront payment");
    }
    // create direct pay
    const createdDirectPay = await directPayService.createDirectPay({
      invoiceId: invoiceId,
      mandateId: mandate[0].id,
      amount: amount,
      buyerId: mandateBuyerId,
      monoCustomerId: mandateMonoCustomerId,
      reference: referenceId,
      monoAccountId: mandateMonoAccountId,
      monoUrl: directPay.data.data.mono_url,
      status: DirectPayStatus.Pending,
    });
    if (!directPay.success) {
      throw new Error("Failed to create direct pay");
    }
    return {
      success: true,
      message: "Upfront payment initiated successfully",
      data: {
        directPay: { ...createdDirectPay, invoiceId, referenceId },
      },
    };
  }
  async validateMandateMandateDownPaymentAndCreateLoanInvoice({
    invoiceId,
    referenceId,
  }: {
    invoiceId?: string;
    referenceId?: string;
  }) {
    let mandate;
    // if (invoiceId) {
    //   const invoiceMandate = await invoiceMandateService.getMandatesByInvoiceId(invoiceId);
    //   if (invoiceMandate?.length > 0) {
    //     mandate = invoiceMandate[0];
    //   }
    // }
    if (referenceId) {
      try {
        mandate = await invoiceMandateService.getMandateByReferenceId(referenceId);
      } catch (error) {
        const directPay = await directPayService.getDirectPayByReference(referenceId);
        if (!directPay) {
          throw new Error("Direct pay not found");
        }
        const invoiceMandate = await invoiceMandateService.getMandatesByInvoiceId(
          directPay.invoiceId
        );
        if (invoiceMandate?.length > 0) {
          mandate = invoiceMandate[0];
        }
      }
    }

    if (!mandate) {
      throw new Error("Mandate not found");
    }
    if (mandate.status != "Active") {
      throw new Error("Mandate emandate not yet authorise");
    }
    // check upfront payment
    const upfrontPayment = await directPayService.getDirectPaysByMandateId(mandate.id);
    if (!upfrontPayment) {
      throw new Error("Upfront payment not found");
    }
    const finalizeResult = await this.finalizeAfterUpfrontAndMandate(mandate.id);
    return finalizeResult;
  }
  // ==================== ITEM CRUD ====================

  /**
   * Create item for an invoice
   */
  async createItem(invoiceId: string, input: CreateItemInput) {
    try {
      // Verify invoice exists
      const invoice = await prisma.invoice.findUnique({
        where: { id: invoiceId },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }

      const item = await prisma.item.create({
        data: {
          invoiceId,
          description: input.description,
          quantity: input.quantity,
          amount: input.amount,
        },
        include: {
          invoice: {
            select: {
              id: true,
              splitrId: true,
              customerName: true,
            },
          },
        },
      });

      return {
        success: true,
        message: "Item created successfully",
        data: item,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to create item",
      };
    }
  }

  /**
   * Get item by ID
   */
  async getItemById(id: string) {
    try {
      const item = await prisma.item.findUnique({
        where: { id },
        include: {
          invoice: {
            select: {
              id: true,
              splitrId: true,
              customerName: true,
              status: true,
            },
          },
        },
      });

      if (!item) {
        throw new Error("Item not found");
      }

      return {
        success: true,
        data: item,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch item",
      };
    }
  }

  /**
   * Get all items for an invoice
   */
  async getItemsByInvoiceId(invoiceId: string) {
    try {
      const items = await prisma.item.findMany({
        where: { invoiceId },
        orderBy: { createdAt: "asc" },
      });

      return {
        success: true,
        data: items,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch items",
      };
    }
  }

  /**
   * Update item
   */
  async updateItem(id: string, input: UpdateItemInput) {
    try {
      const existingItem = await prisma.item.findUnique({
        where: { id },
      });

      if (!existingItem) {
        throw new Error("Item not found");
      }

      const item = await prisma.item.update({
        where: { id },
        data: input,
        include: {
          invoice: {
            select: {
              id: true,
              splitrId: true,
              customerName: true,
            },
          },
        },
      });

      return {
        success: true,
        message: "Item updated successfully",
        data: item,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to update item",
      };
    }
  }

  /**
   * Delete item
   */
  async deleteItem(id: string) {
    try {
      const existingItem = await prisma.item.findUnique({
        where: { id },
      });

      if (!existingItem) {
        throw new Error("Item not found");
      }

      await prisma.item.delete({
        where: { id },
      });

      return {
        success: true,
        message: "Item deleted successfully",
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to delete item",
      };
    }
  }

  // ==================== UTILITY METHODS ====================

  /**
   * Calculate invoice total from items
   */
  async calculateInvoiceTotal(invoiceId: string) {
    try {
      const items = await prisma.item.findMany({
        where: { invoiceId },
      });

      const total = items.reduce((sum, item) => {
        return sum + Number(item.amount) * item.quantity;
      }, 0);

      return {
        success: true,
        data: { total, itemCount: items.length },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to calculate invoice total",
      };
    }
  }

  /**
   * Get invoice statistics for a merchant
   */
  async getMerchantInvoiceStats(merchantId: string) {
    try {
      const [total, pending, paid, cancelled] = await Promise.all([
        prisma.invoice.count({ where: { merchantId } }),
        prisma.invoice.count({
          where: { merchantId, status: InvoiceStatus.Pending },
        }),
        prisma.invoice.count({
          where: { merchantId, status: InvoiceStatus.Paid },
        }),
        prisma.invoice.count({
          where: { merchantId, status: InvoiceStatus.Cancelled },
        }),
      ]);

      const totalAmount = await prisma.invoice.aggregate({
        where: { merchantId },
        _sum: { amount: true },
      });

      const paidAmount = await prisma.invoice.aggregate({
        where: { merchantId, status: InvoiceStatus.Paid },
        _sum: { amount: true },
      });

      const pendingAmount = await prisma.invoice.aggregate({
        where: { merchantId, status: InvoiceStatus.Pending },
        _sum: { amount: true },
      });

      return {
        success: true,
        data: {
          counts: {
            total,
            pending,
            paid,
            cancelled,
          },
          amounts: {
            total: Number(totalAmount._sum.amount || 0),
            paid: Number(paidAmount._sum.amount || 0),
            pending: Number(pendingAmount._sum.amount || 0),
          },
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoice statistics",
      };
    }
  }
  async calculateRefundForInvoice(invoiceId: string) {
    try {
      const invoice = await prisma.invoice.findUnique({
        where: { id: invoiceId },
        include: {
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanStartDate: true,
              loanAmount: true,
              insurance: true,
              adminCharge: true,
              monthlyRepayment: true,
              loanTenure: true,
              loanInterestRate: true,
            },
          },
        },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }
      const loandetails = await loanService.getLoanById(invoice.loan?.id as string);
      if (!loandetails) {
        throw new Error("Loan not found");
      }
      const refund = this.calculateRefund({
        downpayment: Number(invoice.loan?.downPaymentAmount),
        principalPaymentToDate:
          Number(loandetails.data?.loanAmount) - (Number(loandetails.data?.principalBalance) || 0),
        approvalDate: invoice?.returnApprovedDate || new Date(),
        loanStartDate: loandetails.data?.loanStartDate as Date | string,
        currentBalance: Number(loandetails.data?.overallBalance),
        unpaidInterest: Number(loandetails.data?.interestBalance),
        unpaidPenalty: Number(loandetails.data?.penaltyBalance),
      });
      return {
        success: true,
        data: {
          ...refund,
          invoiceId: invoiceId,
          loanId: invoice.loan?.id as string,
          loanamount: Number(invoice.loan?.loanAmount),
          insurance: Number(invoice.loan?.insurance),
          adminCharge: Number(invoice.loan?.adminCharge),
          monthlyRepayment: Number(invoice.loan?.monthlyRepayment),
          loanTenure: Number(invoice.loan?.loanTenure),
          loanInterestRate: Number(invoice.loan?.loanInterestRate),
          loanStartDate: invoice.loan?.loanStartDate as Date | string,
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to calculate refund",
      };
    }
  }
  calculateRefund({
    downpayment = 0,
    principalPaymentToDate = 0,
    approvalDate = new Date(),
    loanStartDate,
    currentBalance = 0,
    unpaidInterest = 0,
    unpaidPenalty = 0,
  }: {
    downpayment?: number;
    principalPaymentToDate?: number;
    approvalDate: Date | string;
    loanStartDate: Date | string;
    currentBalance?: number;
    unpaidInterest?: number;
    unpaidPenalty?: number;
  }) {
    try {
      const REFUND_RATE_PERCENTAGE = 1;
      const INTEREST_RATE = 7.5;

      // Validate approval date
      const approvedDate = new Date(approvalDate);

      if (isNaN(approvedDate.getTime())) {
        throw new Error("Invalid approvalDate provided");
      }
      const loanCommencementDate = new Date(loanStartDate);
      if (isNaN(loanCommencementDate.getTime())) {
        throw new Error("Invalid loanStartDate provided");
      }

      // Difference in days
      const diffInMs = approvedDate.getTime() - loanCommencementDate.getTime();
      const diffInDays = Math.max(0, Math.floor(diffInMs / (1000 * 60 * 60 * 24)));

      // Remainder of (difference / 30)
      const applicableDays = diffInDays % 30;

      // Calculations
      const assumedRefundable = Number(principalPaymentToDate) + Number(downpayment);

      const refundCharge = assumedRefundable * REFUND_RATE_PERCENTAGE * 0.01;

      const interestCharge = applicableDays > 5 ? (currentBalance * INTEREST_RATE * 0.01) / 30 : 0;

      const refundDue =
        assumedRefundable -
        (refundCharge + interestCharge + Number(unpaidInterest) + Number(unpaidPenalty));

      return {
        success: true,

        calculation: {
          assumedRefundable,
          refundCharge,
          applicableDays,
          interestCharge,
          unpaidInterest,
          unpaidPenalty,
          refundDue,
        },
        summary: {
          message: "Refund calculation completed successfully",
          approvalDate: approvedDate.toISOString(),
          loanStartDate: loanCommencementDate.toISOString(),
          totalDeductions:
            refundCharge + interestCharge + Number(unpaidInterest) + Number(unpaidPenalty),
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to calculate refund",
      };
    }
  }
  async buyerFundWithdrawal({
    invoiceId,
    bankCode,
    accountNumber,
  }: {
    invoiceId: string;
    bankCode: string;
    accountNumber: string;
  }) {
    try {
      const invoice = await prisma.invoice.findUnique({
        where: { id: invoiceId },
        include: {
          loan: { select: { id: true } },
        },
      });
      if (!invoice) {
        throw new Error("Invoice not found");
      }
      // if (invoice.status !== InvoiceStatus.Cancelled) {
      //   throw new Error(
      //     'Invoice is still active please contact your merchant to refund the invoice',
      //   );
      // }
      if (invoice.returnStatus === LoanReturnStatus.Refunded) {
        throw new Error("Invoice is already refunded");
      }
      if (invoice.returnStatus !== LoanReturnStatus.Approved) {
        throw new Error("Invoice is not approved for refund");
      }
      const buyerId = invoice.buyerId;
      if (!buyerId) {
        throw new Error("Buyer not found");
      }
      await this.updateInvoice(invoiceId, {
        returnStatus: LoanReturnStatus.Refunded,
      });
      const transferRecipient =
        await paystackMerchantTransferRecipientService.getOrCreateTransferRecipient({
          buyerId: buyerId,
          accountNumber: accountNumber,
          bankCode: bankCode,
        });
      if (!transferRecipient?.success) {
        await this.rollbackRefundStatus(invoiceId, LoanReturnStatus.Approved);

        throw new Error("Failed to get or create transfer recipient");
      }
      const refund = await this.calculateRefundForInvoice(invoiceId);
      if (!refund?.success) {
        await this.rollbackRefundStatus(invoiceId, LoanReturnStatus.Approved);
        throw new Error("Failed to calculate refund");
      }
      // auto generate reference id
      const referenceId = generateShortReferenceId();
      const amount = Number(Number(refund.data?.calculation?.refundDue || 0).toFixed(2));
      const paystackTransfer = await paystackTransferService.createPaystackTransfer({
        referenceId: referenceId,
        merchantId: invoice.merchantId,
        buyerId: buyerId,
        amount,
        recipientCode: transferRecipient.data?.recipientCode || "",
      });
      if (!paystackTransfer?.success) {
        await this.rollbackRefundStatus(invoiceId, LoanReturnStatus.Approved);
        throw new Error("Failed to create paystack transfer");
      }
      const paystackTransferResult = await paystackService.initiateTransfer({
        source: "balance",
        amount: amount * 100,
        recipient: transferRecipient.data?.recipientCode || "",
        reference: referenceId,
      });
      if (!paystackTransferResult?.status) {
        await this.rollbackRefundStatus(invoiceId, LoanReturnStatus.Approved);
        throw new Error("Failed to initiate paystack transfer");
      }
      //verify payment
      const paystackTransferStatus = await paystackService.verifyTransfer(referenceId);
      if (!paystackTransferStatus?.status) {
        await this.rollbackRefundStatus(invoiceId, LoanReturnStatus.Approved);
        throw new Error("Failed to verify paystack transfer");
      }
      if (paystackTransferStatus?.data?.status === "failed") {
        await this.rollbackRefundStatus(invoiceId, LoanReturnStatus.Approved);
        throw new Error("Paystack transfer is failed");
      }
      // update invoice status to refunded
      await this.updateInvoice(invoiceId, {
        returnStatus: LoanReturnStatus.Refunded,
      });
      // update paystack transfer status to completed
      await paystackTransferService.updatePaystackTransfer(paystackTransfer.data?.id as string, {
        status: PaystackTransferStatus.Success,
      });
      await this.updateInvoice(invoiceId, {
        status: InvoiceStatus.Cancelled,
      });
      // update loan status to refunded
      if (!invoice.loan?.id) {
        throw new Error("Loan not found for invoice");
      }
      await loanService.updateLoan(invoice.loan?.id as string, {
        loanStatus: LoanStatus.Cancel,
      });
      return {
        success: true,
        message: "Buyer fund withdrawal successful",
        data: {
          paystackTransfer: paystackTransfer.data,
          paystackTransferResult: paystackTransferResult.data,
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to create paystack transfer",
      };
    }
  }
  async rollbackRefundStatus(invoiceId: string, status: LoanReturnStatus) {
    try {
      await prisma.invoice.update({
        where: { id: invoiceId },
        data: {
          returnStatus: status,
        },
      });
    } catch (error: any) {
      throw new Error(error.message || "Failed to rollback refund status");
    }
  }
  async approveAndCreateLoanInvoiceSplitr(
    id: string,
    installmentType: LoanInstallmentType,
    loanTenure: number,
    downPaymentAmount: number,
    loanAmount: number,
    buyerId: string
  ) {
    const buyer = await prisma.buyer.findUnique({
      where: { id: buyerId },
    });
    if (!buyer) {
      throw new Error("Buyer not found");
    }
    const invoice = await prisma.invoice.findUnique({
      where: { id: id },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }

    const updateData = {
      status: InvoiceStatus.Paid,
      buyer: { connect: { id: buyerId } },
      customerName: `${buyer.firstName ?? ""} ${buyer.lastName ?? ""}`.trim(),
      customerEmail: buyer.email,
      customerPhoneNumber: buyer.phoneNumber ?? invoice.customerPhoneNumber,
      installmentType,
    };

    const updatedInvoice = await prisma.invoice.update({
      where: { id: id },
      data: updateData,
      include: {
        items: true,
      },
    });

    // create invoice mandate
    //generate short alphanumeric referenceId (max 24 characters)
    const referenceId = generateShortReferenceId();
    const interest = installmentType === LoanInstallmentType.Monthly ? Number(INTERST_RATE) : 0;
    const monthlyRate = interest * 0.01;
    const factor = Math.pow(1 + monthlyRate, loanTenure);
    const monthlyRepayment = (loan: number) =>
      monthlyRate === 0 ? loan / loanTenure : (loan * monthlyRate * factor) / (factor - 1);
    const loanResult = await loanService.createLoan({
      buyerId: buyerId,
      invoiceId: id,
      loanAmount: loanAmount,
      loanTenure: loanTenure,
      loanStartDate: new Date(),
      loanStatus: LoanStatus.Active,
      loanType: LoanType.Personal,
      loanInterestRate: interest,
      loanPurpose: "Loan",
      purchaseAmount: Number(invoice.amount),
      downPaymentAmount: downPaymentAmount,
      merchantId: invoice.merchantId ?? undefined,
      referenceNumber: referenceId,
      installmentType: installmentType,
      monthlyRepayment: monthlyRepayment(loanAmount),
    });

    if (!loanResult.success) {
      throw new Error(loanResult.error || "Failed to create loan");
    }

    return {
      success: true,
      message: "Invoice updated successfully",
      data: {
        invoice: updatedInvoice,
        loan: loanResult.data,
      },
    };
  }
}
export const invoiceService = new InvoiceService();
