import {
  TransactionStatus,
  MerchantTransactionType,
  RevenueType,
  PaystackTransferStatus,
  MerchantStatus,
} from "@prisma/client";
import { randomUUID } from "crypto";
import { RevenueService } from "./revenueService";
import prisma from "../utils/prisma";
import { paystackTransferService } from "./paystackTransferService";
import { paystackMerchantTransferRecipientService } from "./paystackMerchantTransferRecipientService";
import { paystackService } from "./paystackService";
import { tierService } from "./tierService";
const revenueService = new RevenueService();
// ==================== INTERFACES ====================

export interface ManualSettlementInput {
  merchantId: string;
  amount: number;
  accountNumberId?: string;
}
export interface CreateMerchantTransactionInput {
  merchantId: string;
  invoiceRef?: string;
  groupReference?: string;
  credit: number;
  debit: number;
  transactionType: MerchantTransactionType;
  transactionDate: Date;
  description: string;
  status?: TransactionStatus;
}

export interface UpdateMerchantTransactionInput {
  credit?: number;
  debit?: number;
  transactionType?: MerchantTransactionType;
  transactionDate?: Date;
  description?: string;
  status?: TransactionStatus;
}

export class MerchantTransactionService {
  // ==================== MERCHANT TRANSACTION CRUD ====================
  bankCharges: number = Number(process.env.BANK_CHARGES) || 100;
  /**
   * Create a new merchant transaction
   */
  async createMerchantTransaction(input: CreateMerchantTransactionInput) {
    try {
      // Validate credit and debit
      if (input.credit > 0 && input.debit > 0) {
        throw new Error(
          "Transaction cannot have both credit and debit amounts"
        );
      }

      if (input.credit === 0 && input.debit === 0) {
        throw new Error("Transaction must have either credit or debit amount");
      }

      // Verify merchant exists
      const merchant = await prisma.merchant.findUnique({
        where: { id: input.merchantId },
      });

      if (!merchant) {
        throw new Error("Merchant not found");
      }

      // Verify invoice exists if provided
      if (input.invoiceRef) {
        const invoice = await prisma.invoice.findUnique({
          where: { id: input.invoiceRef },
        });

        if (!invoice) {
          throw new Error("Invoice not found");
        }

        // Verify invoice belongs to merchant
        if (invoice.merchantId !== input.merchantId) {
          throw new Error("Invoice does not belong to this merchant");
        }
      }

      const transaction = await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          invoiceRef: input.invoiceRef,
          credit: input.credit,
          debit: input.debit,
          transactionType: input.transactionType,
          transactionDate: input.transactionDate,
          description: input.description,
          status: input.status || TransactionStatus.Pending,
        },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              amount: true,
              status: true,
            },
          },
        },
      });

      return { success: true, data: transaction };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get merchant transaction by ID
   */
  async getMerchantTransactionById(transactionId: string) {
    try {
      const transaction = await prisma.merchantTransaction.findUnique({
        where: { id: transactionId },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
              businessCategory: true,
            },
          },
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              amount: true,
              status: true,
              customerName: true,
            },
          },
        },
      });

      if (!transaction) {
        throw new Error("Merchant transaction not found");
      }

      return { success: true, data: transaction };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get merchant transaction by liftpayId
   */
  async getMerchantTransactionByLiftpayId(liftpayId: string) {
    try {
      const transaction = await prisma.merchantTransaction.findUnique({
        where: { liftpayId },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          invoice: true,
        },
      });

      if (!transaction) {
        throw new Error("Merchant transaction not found");
      }

      return { success: true, data: transaction };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get all transactions for a merchant
   */
  async getMerchantTransactionsByMerchantId(
    merchantId: string,
    filters?: {
      transactionType?: MerchantTransactionType | MerchantTransactionType[];
      status?: TransactionStatus;
      startDate?: Date;
      endDate?: Date;
      page?: number;
      limit?: number;
    }
  ) {
    try {
      const page = filters?.page || 1;
      const limit = filters?.limit || 10;
      const skip = (page - 1) * limit;

      const where: any = { merchantId };
      if (filters?.transactionType) {
        // Support both single value and array of values
        if (Array.isArray(filters.transactionType)) {
          where.transactionType = { in: filters.transactionType };
        } else {
          where.transactionType = filters.transactionType;
        }
      }
      if (filters?.status) where.status = filters.status;

      // Date range filtering
      if (filters?.startDate || filters?.endDate) {
        where.transactionDate = {};
        if (filters?.startDate) {
          where.transactionDate.gte = filters.startDate;
        }
        if (filters?.endDate) {
          where.transactionDate.lte = filters.endDate;
        }
      }

      const [transactions, total] = await Promise.all([
        prisma.merchantTransaction.findMany({
          where,
          skip,
          take: limit,
          include: {
            invoice: {
              select: {
                id: true,
                liftpayId: true,
                amount: true,
                status: true,
              },
            },
          },
          orderBy: [{ transactionDate: "desc" }, { createdAt: "desc" }],
        }),
        prisma.merchantTransaction.count({ where }),
      ]);

      return {
        success: true,
        data: {
          transactions,
          pagination: {
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
          },
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get all merchant transactions with filters
   */
  async getAllMerchantTransactions(filters?: {
    merchantId?: string;
    transactionType?: MerchantTransactionType | MerchantTransactionType[];
    status?: TransactionStatus;
    startDate?: Date;
    endDate?: Date;
    page?: number;
    limit?: number;
  }) {
    try {
      const page = filters?.page || 1;
      const limit = filters?.limit || 10;
      const skip = (page - 1) * limit;

      const where: any = {};
      if (filters?.merchantId) where.merchantId = filters.merchantId;
      if (filters?.transactionType) {
        // Support both single value and array of values
        if (Array.isArray(filters.transactionType)) {
          where.transactionType = { in: filters.transactionType };
        } else {
          where.transactionType = filters.transactionType;
        }
      }
      if (filters?.status) where.status = filters.status;

      // Date range filtering
      if (filters?.startDate || filters?.endDate) {
        where.transactionDate = {};
        if (filters?.startDate) {
          where.transactionDate.gte = filters.startDate;
        }
        if (filters?.endDate) {
          where.transactionDate.lte = filters.endDate;
        }
      }

      const [transactions, total] = await Promise.all([
        prisma.merchantTransaction.findMany({
          where,
          skip,
          take: limit,
          include: {
            merchant: {
              select: {
                id: true,
                liftpayId: true,
                businessName: true,
                businessEmail: true,
              },
            },
            invoice: {
              select: {
                id: true,
                liftpayId: true,
                amount: true,
                status: true,
              },
            },
          },
          orderBy: [{ transactionDate: "desc" }, { createdAt: "desc" }],
        }),
        prisma.merchantTransaction.count({ where }),
      ]);

      return {
        success: true,
        data: {
          transactions,
          pagination: {
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
          },
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Update merchant transaction
   */
  async updateMerchantTransaction(
    transactionId: string,
    input: UpdateMerchantTransactionInput
  ) {
    try {
      // Validate credit and debit if both are provided
      if (
        input.credit !== undefined &&
        input.debit !== undefined &&
        input.credit > 0 &&
        input.debit > 0
      ) {
        throw new Error(
          "Transaction cannot have both credit and debit amounts"
        );
      }

      const transaction = await prisma.merchantTransaction.update({
        where: { id: transactionId },
        data: input,
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              amount: true,
              status: true,
            },
          },
        },
      });

      return { success: true, data: transaction };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Complete a merchant transaction
   */
  async completeMerchantTransaction(transactionId: string) {
    try {
      const transaction = await prisma.merchantTransaction.update({
        where: { id: transactionId },
        data: {
          status: TransactionStatus.Completed,
        },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      return {
        success: true,
        data: transaction,
        message: "Transaction completed successfully",
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Delete merchant transaction
   */
  async deleteMerchantTransaction(transactionId: string) {
    try {
      const transaction = await prisma.merchantTransaction.delete({
        where: { id: transactionId },
      });

      return {
        success: true,
        data: transaction,
        message: "Merchant transaction deleted successfully",
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get merchant balance (sum of credit - debit)
   */
  async getMerchantBalance(merchantId: string) {
    try {
      const transactions = await prisma.merchantTransaction.findMany({
        where: {
          merchantId,
          status: TransactionStatus.Completed,
        },
      });

      const totalCredit = transactions.reduce(
        (sum, t) => sum + Number(t.credit),
        0
      );
      const totalDebit = transactions.reduce(
        (sum, t) => sum + Number(t.debit),
        0
      );
      const balance = totalCredit - totalDebit;

      // Group by transaction type
      const balanceByType: Record<
        string,
        {
          transactionType: MerchantTransactionType;
          balance: number;
          totalCredit: number;
          totalDebit: number;
          transactionCount: number;
        }
      > = {};

      Object.values(MerchantTransactionType).forEach((type) => {
        balanceByType[type] = {
          transactionType: type,
          balance: 0,
          totalCredit: 0,
          totalDebit: 0,
          transactionCount: 0,
        };
      });

      transactions.forEach((transaction) => {
        const type = transaction.transactionType;
        const credit = Number(transaction.credit);
        const debit = Number(transaction.debit);

        balanceByType[type].totalCredit += credit;
        balanceByType[type].totalDebit += debit;
        balanceByType[type].balance += credit - debit;
        balanceByType[type].transactionCount += 1;
      });

      const result = Object.values(balanceByType).filter(
        (item) => item.transactionCount > 0
      );

      return {
        success: true,
        data: {
          merchantId,
          balance,
          totalCredit,
          totalDebit,
          transactionCount: transactions.length,
          balanceByType: result,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get all merchants with their balances (sum of credit - debit)
   */
  async getAllMerchantsWithBalances() {
    try {
      // Get all merchants
      const merchants = await prisma.merchant.findMany({
        where: {
          isDeleted: false,
          isAgreedToTerms: true,
          applicationStatus: MerchantStatus.Approved,
          verificationStatus: MerchantStatus.Approved,
        },
        select: {
          id: true,
          liftpayId: true,
          businessName: true,
          businessEmail: true,
        },
      });

      // Get all completed transactions grouped by merchant
      const allTransactions = await prisma.merchantTransaction.findMany({
        where: {
          status: TransactionStatus.Completed,
        },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      // Group transactions by merchant
      const transactionsByMerchant: Record<
        string,
        typeof allTransactions
      > = {};

      allTransactions.forEach((transaction) => {
        const merchantId = transaction.merchantId;
        if (!transactionsByMerchant[merchantId]) {
          transactionsByMerchant[merchantId] = [];
        }
        transactionsByMerchant[merchantId].push(transaction);
      });

      // Calculate balance for each merchant
      const merchantsWithBalances = merchants.map((merchant) => {
        const transactions = transactionsByMerchant[merchant.id] || [];

        const totalCredit = transactions.reduce(
          (sum, t) => sum + Number(t.credit),
          0
        );
        const totalDebit = transactions.reduce(
          (sum, t) => sum + Number(t.debit),
          0
        );
        const balance = totalCredit - totalDebit;

        // Group by transaction type
        const balanceByType: Record<
          string,
          {
            transactionType: MerchantTransactionType;
            balance: number;
            totalCredit: number;
            totalDebit: number;
            transactionCount: number;
          }
        > = {};

        Object.values(MerchantTransactionType).forEach((type) => {
          balanceByType[type] = {
            transactionType: type,
            balance: 0,
            totalCredit: 0,
            totalDebit: 0,
            transactionCount: 0,
          };
        });

        transactions.forEach((transaction) => {
          const type = transaction.transactionType;
          const credit = Number(transaction.credit);
          const debit = Number(transaction.debit);

          balanceByType[type].totalCredit += credit;
          balanceByType[type].totalDebit += debit;
          balanceByType[type].balance += credit - debit;
          balanceByType[type].transactionCount += 1;
        });

        const balanceByTypeResult = Object.values(balanceByType).filter(
          (item) => item.transactionCount > 0
        );

        return {
          merchantId: merchant.id,
          liftpayId: merchant.liftpayId,
          businessName: merchant.businessName,
          businessEmail: merchant.businessEmail,
          balance,
          totalCredit,
          totalDebit,
          transactionCount: transactions.length,
          balanceByType: balanceByTypeResult,
        };
      });

      return {
        success: true,
        data: {
          merchants: merchantsWithBalances,
          totalMerchants: merchants.length,
          totalMerchantsWithTransactions: merchantsWithBalances.filter(
            (m) => m.transactionCount > 0
          ).length,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }
  /**
   * Get sum of credit grouped by merchantId where transactionType is Credit and isSettled = false
   */
  async getUnsettledCreditByMerchant() {
    try {
      const transactions = await prisma.merchantTransaction.findMany({
        where: {
          transactionType: MerchantTransactionType.Credit,
          isSettled: false,
        },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      // Group by merchant and sum credits
      const creditByMerchant: Record<
        string,
        {
          merchantId: string;
          liftpayId: string;
          businessName: string;
          businessEmail: string;
          totalCredit: number;
          transactionCount: number;
        }
      > = {};

      transactions.forEach((transaction) => {
        const merchantId = transaction.merchantId;
        if (!creditByMerchant[merchantId]) {
          creditByMerchant[merchantId] = {
            merchantId: merchantId,
            liftpayId: transaction.merchant.liftpayId,
            businessName: transaction.merchant.businessName,
            businessEmail: transaction.merchant.businessEmail,
            totalCredit: 0,
            transactionCount: 0,
          };
        }
        creditByMerchant[merchantId].totalCredit += Number(transaction.credit);
        creditByMerchant[merchantId].transactionCount += 1;
      });

      return {
        success: true,
        data: {
          creditByMerchant: Object.values(creditByMerchant),
          totalMerchants: Object.keys(creditByMerchant).length,
          totalCredit: transactions.reduce(
            (sum, t) => sum + Number(t.credit),
            0
          ),
          totalTransactions: transactions.length,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get sum of credit for a specific merchantId where transactionType is Credit and isSettled = false
   */
  async getUnsettledCreditByMerchantId(merchantId: string) {
    try {
      const transactions = await prisma.merchantTransaction.findMany({
        where: {
          merchantId,
          transactionType: MerchantTransactionType.Credit,
          isSettled: false,
        },
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      const totalCredit = transactions.reduce(
        (sum, t) => sum + Number(t.credit),
        0
      );

      return {
        success: true,
        data: {
          merchantId,
          liftpayId: transactions[0]?.merchant?.liftpayId || null,
          businessName: transactions[0]?.merchant?.businessName || null,
          businessEmail: transactions[0]?.merchant?.businessEmail || null,
          totalCredit,
          transactionCount: transactions.length,
          transactions,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Update isSettled to true for all transactions where merchantId matches and transactionType is Credit
   */
  async settleCreditTransactionsByMerchantId(merchantId: string) {
    try {
      // Verify merchant exists
      const merchant = await prisma.merchant.findUnique({
        where: { id: merchantId },
        select: {
          id: true,
          liftpayId: true,
          businessName: true,
        },
      });

      if (!merchant) {
        throw new Error("Merchant not found");
      }

      // Get count of transactions that will be updated
      const countBeforeUpdate = await prisma.merchantTransaction.count({
        where: {
          merchantId,
          transactionType: MerchantTransactionType.Credit,
          isSettled: false,
        },
      });

      // Update all matching transactions
      const updateResult = await prisma.merchantTransaction.updateMany({
        where: {
          merchantId,
          transactionType: MerchantTransactionType.Credit,
          isSettled: false,
        },
        data: {
          isSettled: true,
        },
      });

      // Get the updated transactions for response
      const updatedTransactions = await prisma.merchantTransaction.findMany({
        where: {
          merchantId,
          transactionType: MerchantTransactionType.Credit,
          isSettled: true,
        },
        orderBy: {
          updatedAt: "desc",
        },
        take: countBeforeUpdate, // Get the recently updated ones
      });

      // Calculate total credit that was settled
      const totalSettledCredit = updatedTransactions.reduce(
        (sum, t) => sum + Number(t.credit),
        0
      );

      return {
        success: true,
        data: {
          merchantId,
          liftpayId: merchant.liftpayId,
          businessName: merchant.businessName,
          transactionsUpdated: updateResult.count,
          totalSettledCredit,
          message: `Successfully settled ${updateResult.count} credit transaction(s) for merchant`,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get unsettled revenue (sum of credits where isSettled = false and transactionType = Credit)
   */
  async getUnsettledRevenue(merchantId?: string) {
    try {
      const where: any = {
        isSettled: false,
        status: TransactionStatus.Completed,
      };

      if (merchantId) {
        where.merchantId = merchantId;
      }

      const transactions = await prisma.merchantTransaction.findMany({
        where,
        include: {
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              amount: true,
            },
          },
        },
      });

      // Calculate total unsettled revenue as difference between credit and debit
      const totalCredit = transactions.reduce(
        (sum, t) => sum + Number(t.credit),
        0
      );
      const totalDebit = transactions.reduce(
        (sum, t) => sum + Number(t.debit),
        0
      );
      const totalUnsettledRevenue = totalCredit - totalDebit;

      // Group by merchant if no merchantId is provided
      let revenueByMerchant: Record<
        string,
        {
          merchantId: string;
          merchantName: string;
          unsettledRevenue: number;
          transactionCount: number;
        }
      > = {};

      if (!merchantId) {
        transactions.forEach((transaction) => {
          const mid = transaction.merchantId;
          if (!revenueByMerchant[mid]) {
            revenueByMerchant[mid] = {
              merchantId: mid,
              merchantName: transaction.merchant.businessName,
              unsettledRevenue: 0,
              transactionCount: 0,
            };
          }
          // Calculate net revenue (credit - debit) for each merchant
          revenueByMerchant[mid].unsettledRevenue +=
            Number(transaction.credit) - Number(transaction.debit);
          revenueByMerchant[mid].transactionCount += 1;
        });
      }

      return {
        success: true,
        data: {
          merchantId: merchantId || null,
          totalUnsettledRevenue,
          totalCredit,
          totalDebit,
          transactionCount: transactions.length,
          transactions: merchantId ? transactions : undefined,
          revenueByMerchant: !merchantId
            ? Object.values(revenueByMerchant)
            : undefined,
        },
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  async manualSettlement(input: ManualSettlementInput) {
    try {
      // Verify merchant exists
      const merchant = await this.getMerchantWithBanks(input.merchantId);
      if (!merchant) {
        throw new Error("Merchant not found");
      }
      // get merchant charge
      const merchantCharge = Number(merchant.merchantCharge);
      if (!merchantCharge) {
        throw new Error("Merchant charge not found");
      }
      // verify account number id inside merchant account details
      const merchantBankAccount = merchant.banks
      if (!merchantBankAccount.some((bank) => bank.id === input.accountNumberId)) {
        throw new Error("Merchant bank account not found");
      }
      const accountNumber = merchantBankAccount.find((bank) => bank.id === input.accountNumberId)?.accountNumber;
      const bankCode = merchantBankAccount.find((bank) => bank.id === input.accountNumberId)?.bank.bankCode;
      if (!accountNumber || !bankCode) {
        throw new Error("Account number or bank code not found");
      }
      const paystackTransferRecipient = await paystackMerchantTransferRecipientService.getOrCreatePaystackMerchantTransferRecipient(input.merchantId, accountNumber, bankCode);
      if (!paystackTransferRecipient.success) {
        throw new Error("Paystack transfer recipient not found");
      }
      // throw new Error("we are testing the paystack transfer recipient");
      // calculate merchant charge amount

      // get merchant balance
      const merchantBalance = await this.getMerchantBalance(input.merchantId);
      if (!merchantBalance) {
        throw new Error("Merchant balance not found");
      }
      if (Number(merchantBalance.data?.balance) < Number(input.amount)) {
        throw new Error("Merchant balance is not enough");
      }
      const marchantFee = input.amount * merchantCharge * 0.01;
      const balance = input.amount - this.bankCharges - marchantFee;
      // const { withdrawable, charge } = this.maxWithdrawable(
      //   balance,
      //   input.amount
      // );

      //generate group reference
      const groupReference = randomUUID();
      await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          groupReference: groupReference,
          credit: 0,
          debit: this.bankCharges,
          transactionType: MerchantTransactionType.PayoutCharge,
          transactionDate: new Date(),
          description: `Bank charges of ${this.bankCharges}`,
          status: TransactionStatus.Pending,
        },
      });
      await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          groupReference: groupReference,
          credit: 0,
          debit: marchantFee,
          transactionType: MerchantTransactionType.MerchantCharge,
          transactionDate: new Date(),
          description: `Merchant charge of ${marchantFee}`,
          status: TransactionStatus.Pending,
        },
      });
      const transaction = await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          groupReference: groupReference,
          credit: 0,
          debit: balance,
          transactionType: MerchantTransactionType.ManualSettlement,
          transactionDate: new Date(),
          description: `Manual settlement of ${balance}`,
          status: TransactionStatus.Pending,
        },
      });

      await revenueService.createRevenue({
        type: RevenueType.Settlement,
        credit: 0,
        debit: input.amount,
        description: `Manual settlement of ${input.amount}`,
        referenceIds: [groupReference],
        transactionDate: new Date(),
        parentTable: "merchantTransaction",
        merchantId: input.merchantId,
      });
      // get paystack transfer recipient
      //  create paystack transfer
      const paystackTransfer = await paystackTransferService.createPaystackTransfer({
        referenceId: groupReference,
        merchantId: input.merchantId,
        amount: balance,
        recipientCode: paystackTransferRecipient.data?.recipientCode || "RCP_39c267e3a0kpohn",
        status: PaystackTransferStatus.Pending,
      });
      if (!paystackTransfer.success) {
        throw new Error("Paystack transfer not created");
      }
      // initiate transfer to paystack
      const paystackTransferResult = await paystackService.initiateTransfer({
        source: "balance",
        amount: balance*100,
        recipient: paystackTransferRecipient.data?.recipientCode || "RCP_39c267e3a0kpohn",
        reference: groupReference,
      });

      // verify transfer status
      const paystackTransferStatus = await paystackService.verifyTransfer(groupReference);
      if (paystackTransferStatus.status && paystackTransferStatus.data.status) {
          // update merchant transaction status to completed
          await prisma.merchantTransaction.updateMany({
            where: { groupReference: groupReference },
            data: {
              status: TransactionStatus.Completed,
            },
          });
        
      }
      return { success: true, data: { message: "Manual settlement initiated successfully" } };
    } catch (error: any) {
      console.error("Error in manual settlement", error);
      return { success: false, error: error.message };
    }
  }
  /**
   * Reusable fetch: merchant with charge and bank accounts + bank info
   */
  private async getMerchantWithBanks(merchantId: string) {
    return prisma.merchant.findUnique({
      where: { id: merchantId },
      select: {
        merchantCharge: true,
        banks: {
          select: {
            id: true,
            accountNumber: true,
            accountName: true,
            bank: {
              select: {
                id: true,
                bankName: true,
                bankCode: true,
              },
            },
          },
        },
      },
    });
  }
  maxWithdrawable(balance: number, chargePercent: number) {
    const withdrawable = balance / (1 + chargePercent / 100);
    const charge = balance - withdrawable;
    return { withdrawable, charge };
  }

  async automaticSettlement() {


    //get all with unsettled credit
    
  
    const merchants = await this.getUnsettledCreditByMerchant();
    if (!merchants.success) {
      throw new Error("Failed to get merchants with balances");

    }
    
    const merchantsWithBalances = merchants.data?.creditByMerchant || [];
    for (const merchant of merchantsWithBalances) {
      // get each merchant unsettled credit
      const unsettledCredit = await this.getUnsettledCreditByMerchantId(merchant.merchantId);
      if (!unsettledCredit.success) {
        // throw new Error("Failed to get unsettled credit");
        console.error(`Failed to get unsettled credit for merchant ${merchant.merchantId}: ${unsettledCredit.error}`);
        continue;
      }
    //check if the merchant have valid bank account
    const merchantWithBanks = await this.getMerchantWithBanks(merchant.merchantId);
    if (!merchantWithBanks) {
      console.error(`Merchant not found for merchant ${merchant.merchantId} ${merchant.businessName}. Skipping this merchant.`);
      continue;
    }
    if (!merchantWithBanks.banks.length) {
      console.error(`Merchant ${merchant.merchantId} ${merchant.businessName} has no valid bank account. Skipping this merchant.`);
      continue;
    }
    // check paystack transfer recipient
    const paystackTransferRecipient = await paystackMerchantTransferRecipientService.getOrCreatePaystackMerchantTransferRecipient(
      merchant.merchantId,
      merchantWithBanks.banks[0].accountNumber,
      merchantWithBanks.banks[0].bank.bankCode
    );

    if (!paystackTransferRecipient.success || !paystackTransferRecipient.data?.recipientCode) {
      console.error(`Paystack transfer recipient not found for merchant ${merchant.merchantId} ${merchant.businessName} Skipping this merchant.`);
      continue;
    }
      // get discount for the merchant
      const unsettledCreditAmount = Number(unsettledCredit.data?.totalCredit || 0);
      const discount = await tierService.calculateDiscount(unsettledCreditAmount );
      let discountAmount = 0;
      if (discount.success) {
        discountAmount = discount.data?.discountAmount || 0;
      }else{
        discountAmount = 0
        console.error(`Failed to get discount for merchant ${merchant.merchantId}: ${discount.error}`);
      }
      
      if (discountAmount > 0) {
        // create a manual settlement for the merchant
        await this.createMerchantTransaction({
          merchantId: merchant.merchantId,
          credit: discountAmount ,
          debit: 0,
          transactionType: MerchantTransactionType.Other,
          transactionDate: new Date(),
          description: `Transaction disount of ${unsettledCreditAmount}`,
          status: TransactionStatus.Completed,
        });
      }
      // update merchant merchant trasaction to isSettled = true
      await prisma.merchantTransaction.updateMany({
        where: { merchantId: merchant.merchantId, transactionType: MerchantTransactionType.Credit, isSettled: false },
        data: { isSettled: true, status: TransactionStatus.Completed },
      });
    }

 
    const merchants22 = await this.getAllMerchantsWithBalances();
    if (!merchants22.success) {
      throw new Error("Failed to get merchants with balances");
    }
    const merchantsWithBalances2 = merchants22.data?.merchants || [];
    
    // Collect all internal settlements
    const settlements: Array<{
      merchantId: string;
      balance: number;
      groupReference: string;
    }> = [];

    for (const merchant of merchantsWithBalances2) {
      // Skip merchants with balance less than or equal to 0
      if (Number(merchant.balance) <= 0) {
        continue;
      }

      // call internal settlement
      const internalSettlement = await this.internalSettlement({ 
        merchantId: merchant.merchantId, 
        amount: Number(merchant.balance) 
      });
      if (!internalSettlement.success) {
        throw new Error(`Failed to internal settlement for merchant ${merchant.merchantId}: ${internalSettlement.error}`);
      }
      
      // Collect successful settlement data
      if (internalSettlement.data) {
        settlements.push({
          merchantId: merchant.merchantId,
          balance: internalSettlement.data.balance,
          groupReference: internalSettlement.data.groupReference,
        });
      }
    }

    // Build bulk transfer array
    const transfers: Array<{
      amount: number;
      reference: string;
      reason: string;
      recipient: string;
    }> = [];

    for (const settlement of settlements) {
      // Get recipient code for each merchant
      const merchant = await this.getMerchantWithBanks(settlement.merchantId);
      if (!merchant) {
        console.error(`Merchant not found for merchant ${settlement.merchantId}. Skipping this merchant.`);
        continue; // Skip this merchant and continue with the next one
      }
      const paystackTransferRecipient = await paystackMerchantTransferRecipientService.getOrCreatePaystackMerchantTransferRecipient(
        settlement.merchantId,
        merchant.banks[0].accountNumber,
        merchant.banks[0].bank.bankCode
      );
      
      if (!paystackTransferRecipient.success || !paystackTransferRecipient.data?.recipientCode) {
        console.error(`Paystack transfer recipient not found for merchant ${settlement.merchantId}. Skipping this merchant.`);
        continue; // Skip this merchant and continue with the next one
      }

      transfers.push({
        amount: settlement.balance * 100, // Convert to kobo
        reference: settlement.groupReference,
        reason: `Automatic settlement of ${settlement.balance}`,
        recipient: paystackTransferRecipient.data.recipientCode,
      });
    }

    // Initiate bulk transfer if there are transfers to process
    if (transfers.length > 0) {
      const bulkTransferResult = await paystackService.initiateBulkTransfer({
        currency: "NGN",
        source: "balance",
        transfers: transfers,
      });

      // Verify each transfer and update merchant transactions in the background (non-blocking)
      if (bulkTransferResult.status && bulkTransferResult.data) {
        // Process verifications in background without blocking the response
        Promise.allSettled(
          bulkTransferResult.data.map(async (transferResult) => {
            try {
              // Verify transfer status using the reference
              const paystackTransferStatus = await paystackService.verifyTransfer(
                transferResult.reference
              );
              
              // If transfer is successful, update merchant transactions to completed
              if (
                paystackTransferStatus.status &&
                paystackTransferStatus.data.status
              ) {
                await prisma.merchantTransaction.updateMany({
                  where: { groupReference: transferResult.reference },
                  data: {
                    status: TransactionStatus.Completed,
                  },
                });
              }
            } catch (error: any) {
              // Log error but continue with other transfers
              console.error(
                `Error verifying transfer ${transferResult.reference}:`,
                error.message
              );
            }
          })
        ).catch((error) => {
          // Log any unexpected errors in the background process
          console.error("Error in background transfer verification:", error);
        });
        // Note: We don't await the Promise.allSettled, so it runs in the background
      }

      return { 
        success: true, 
        data: { 
          message: "Automatic settlement completed successfully",
          settlementsProcessed: settlements.length,
          bulkTransferResult: bulkTransferResult,
        } 
      };
    }

    return { success: true, data: { message: "Automatic settlement completed successfully - no transfers to process" } };
  }

  async internalSettlement(input: ManualSettlementInput) {
    try {
      // Verify merchant exists
      const merchant = await prisma.merchant.findUnique({
        where: { id: input.merchantId },
        select: {
          merchantCharge: true,
          banks: {
            select: {
              id: true,
              accountNumber: true,
              accountName: true,
              bank: {
                select: {
                  id: true,
                  bankName: true,
                  bankCode: true,
              },
            },
            },
          },
        },
      });

      if (!merchant) {
        throw new Error("Merchant not found");
      }
      // get merchant charge
      const merchantCharge = Number(merchant.merchantCharge);
      if (!merchantCharge) {
        throw new Error("Merchant charge not found");
      }
      //verify account number id inside merchant account details
      // const merchantBankAccount = merchant.banks
      // if (!merchantBankAccount.some((bank) => bank.id === input.accountNumberId)) {
      //   throw new Error("Merchant bank account not found");
      // }
      // const accountNumber = merchantBankAccount.find((bank) => bank.id === input.accountNumberId)?.accountNumber;
      // const bankCode = merchantBankAccount.find((bank) => bank.id === input.accountNumberId)?.bank.bankCode;
      // if (!accountNumber || !bankCode) {
      //   throw new Error("Account number or bank code not found");
      // }


      // calculate merchant charge amount

      // get merchant balance
      const merchantBalance = await this.getMerchantBalance(input.merchantId);
      if (!merchantBalance) {
        throw new Error("Merchant balance not found");
      }
      if (Number(merchantBalance.data?.balance) < Number(input.amount)) {
        throw new Error("Merchant balance is not enough");
      }
      const marchantFee = input.amount * merchantCharge * 0.01;
      const balance = input.amount - this.bankCharges - marchantFee;
      
      const groupReference = randomUUID();
      await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          groupReference: groupReference,
          credit: 0,
          debit: this.bankCharges,
          transactionType: MerchantTransactionType.PayoutCharge,
          transactionDate: new Date(),
          description: `Bank charges of ${this.bankCharges}`,
          status: TransactionStatus.Pending,
        },
      });
      await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          groupReference: groupReference,
          credit: 0,
          debit: marchantFee,
          transactionType: MerchantTransactionType.MerchantCharge,
          transactionDate: new Date(),
          description: `Merchant charge of ${marchantFee}`,
          status: TransactionStatus.Pending,
        },
      });
      const transaction = await prisma.merchantTransaction.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          merchantId: input.merchantId,
          groupReference: groupReference,
          credit: 0,
          debit: balance,
          transactionType: MerchantTransactionType.ManualSettlement,
          transactionDate: new Date(),
          description: `Manual settlement of ${balance}`,
          status: TransactionStatus.Pending,
        },
      });

      await revenueService.createRevenue({
        type: RevenueType.Settlement,
        credit: 0,
        debit: input.amount,
        description: `Manual settlement of ${input.amount}`,
        referenceIds: [groupReference],
        transactionDate: new Date(),
        parentTable: "merchantTransaction",
        merchantId: input.merchantId,
      });
      
      return { 
        success: true, 
        data: { 
          merchantId: input.merchantId,
          balance, 
          marchantFee, 
          bankCharges: this.bankCharges, 
          groupReference 
        } 
      };
    } catch (error: any) {
      console.error("Error in internal settlement", error);
      return { success: false, error: error.message };
    }
  }
}

export const merchantTransactionService = new MerchantTransactionService();